name: Running Pytest

on:
  push:
    branches:
      - main
    # - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  tests:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./app

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          make install
      - name: Running Tests
        run: |
          make test
